name: dart_sdk
description: >-
  Dart SDK for ConfigCat. ConfigCat is a hosted feature flag service: https://configcat.com. Manage feature toggles across frontend, backend, mobile, desktop apps. Alternative to LaunchDarkly. Management app + feature flag SDKs.
version: 1.0.0
homepage: https://github.com/configcat/dart-sdk

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  http: ^0.13.3
  logging: ^1.0.1
  tuple: ^2.0.0
  version: ^2.0.0

dev_dependencies:
  test: ^1.17.10
  mockito: ^5.0.15
  build_runner: ^2.1.1